version: '3'
services:
  english-cram-school_web:
    build: .
    volumes:
      - ./web:/var/www/html/english-cram-school
      - dbsocket:/var/run/mysqld
    ports:
      - 8081:8081
      - 3000:3000
  english-cram-school_database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=ecsdb
      - MYSQL_ROOT_PASSWORD=root
      - DB_SOCKET=/var/run/mysqld/mysqld.sock
    volumes:
      - ./database:/var/lib/mysql
      - dbsocket:/var/run/mysqld
    ports:
      - 5434:5432
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=english-cram-school_database
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - english-cram-school_database
    ports:
      - 8080:80
    volumes:
      - /sessions
volumes:
  dbsocket: